//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalonService.Areas.AdminPart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int ID { get; set; }
        public Nullable<int> ID_Person_From { get; set; }
        public string MessageBody { get; set; }
        public Nullable<int> ID_Person_To { get; set; }
        public Nullable<bool> IsRead { get; set; }
        public string MessageTitle { get; set; }
        public Nullable<System.DateTime> SendDate { get; set; }
        public Nullable<System.DateTime> ReadDate { get; set; }
    }
}
