//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalonService.Areas.AdminPart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string Email { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public Nullable<int> ID_SecurityQuestion { get; set; }
        public string SecurityAnswer { get; set; }
        public Nullable<int> ID_Role { get; set; }
        public string CellPhoneNo { get; set; }
        public Nullable<int> ID_Pic { get; set; }
        public string CreatedDate { get; set; }
        public string ModifiedDate { get; set; }
        public Nullable<byte> ApprovedState { get; set; }
    }
}
