//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalonService.Areas.AdminPart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalonService
    {
        public int ID_Service { get; set; }
        public int ID_Salon { get; set; }
        public string Comment { get; set; }
        public Nullable<int> ID_Pic { get; set; }
    }
}
