//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalonService.Areas.AdminPart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalonPhone
    {
        public int ID { get; set; }
        public string PhoneNo { get; set; }
        public Nullable<bool> Type { get; set; }
    }
}
