//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeautySalonService.Areas.AdminPart.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitor
    {
        public int ID { get; set; }
        public string Vis_Date { get; set; }
        public string Vis_IP { get; set; }
        public string Vis_Browser { get; set; }
        public string Vis_Platform { get; set; }
        public string Vis_Referer { get; set; }
        public Nullable<int> IDRelated { get; set; }
        public string Controller { get; set; }
        public string PageName { get; set; }
    }
}
